import Head from 'next/head'
import { ReactNode } from 'react'

type LayoutProps = {
    children: ReactNode
}
export default function Layout({ children }: LayoutProps) {
    return (
        <>
            <Head>
                <title>Farmer Jims Food & Fungi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
        </>
    )
}
