import Head from 'next/head'
import { ReactNode } from 'react'
import NavBar from '../components/NavBar';
import Hero from '../components/Hero';
import Footer from '@/components/Footer';

type LayoutProps = {
    children: ReactNode,
    isLandingPage?: boolean;
}
export default function Layout({ children, isLandingPage }: LayoutProps) {
    return (
        <>
            <Head>
                <title>Farmer Jims Food & Fungi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-gray-50 min-h-screen'>
                <NavBar routes={[]} />
                <Hero isLandingPage={isLandingPage} title="Farmer Jim's" subTitle="Food and Fungi" />
                <div className='mb-20 over'>
                    {children}
                </div>
                <Footer isLandingPage={isLandingPage} />
            </main>
        </>
    )
}
